# Generated by Django 5.0.6 on 2024-05-15 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoSocialApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='idNumber',
            field=models.CharField(default=1, max_length=32, verbose_name='身份证号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(default='普通用户', max_length=16, verbose_name='用户类型'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(default='http://127.0.0.1:8000/media/user/b_cae0faddf4048b65150e57e3b36ed341.jpg', max_length=255, null=True, verbose_name='头像'),
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailTopic', models.CharField(max_length=32, verbose_name='邮件主题')),
                ('emailContent', models.CharField(max_length=255, verbose_name='邮件内容')),
                ('sendTime', models.CharField(max_length=64, verbose_name='发送时间')),
                ('receiveId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='收件人id', to='emoSocialApp.user')),
                ('sendId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='发件人id', to='emoSocialApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Fans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fansId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='粉丝id', to='emoSocialApp.user')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='关注的人id', to='emoSocialApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='用户好友id', to='emoSocialApp.user')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='用户id', to='emoSocialApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='FriendsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiveRequestId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='接受请求id', to='emoSocialApp.user')),
                ('sendRequestId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='发出请求id', to='emoSocialApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Moments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postTime', models.CharField(max_length=64, verbose_name='发布时间')),
                ('postContent', models.CharField(max_length=255, verbose_name='发布内容')),
                ('postPic', models.CharField(max_length=255, null=True, verbose_name='发布图片地址')),
                ('postVideo', models.CharField(max_length=255, null=True, verbose_name='发布视频地址')),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='发布人id', to='emoSocialApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='MomentsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentContent', models.CharField(max_length=64, null=True, verbose_name='评论内容')),
                ('commentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='评论人id', to='emoSocialApp.user')),
                ('momentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='所属朋友圈id', to='emoSocialApp.moments')),
            ],
        ),
        migrations.CreateModel(
            name='MomentsLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likeId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='点赞人id', to='emoSocialApp.user')),
                ('momentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='点赞朋友圈id', to='emoSocialApp.moments')),
            ],
        ),
    ]
