# Generated by Django 5.0.6 on 2024-05-15 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoSocialApp', '0002_user_idnumber_alter_user_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postTopic', models.CharField(max_length=64, verbose_name='公告标题')),
                ('postContent', models.CharField(max_length=255, verbose_name='公告内容')),
                ('postTime', models.CharField(max_length=64, verbose_name='发布时间')),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='公告发布人id', to='emoSocialApp.user')),
            ],
        ),
    ]
