# Generated by Django 5.0.6 on 2024-05-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoSocialApp', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profileBp',
            field=models.CharField(default='src/profile_bp/bp2.jpg', max_length=255, null=True, verbose_name='背景图片'),
        ),
    ]
