# Generated by Django 5.0.6 on 2024-05-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoSocialApp', '0005_userprofile_profilebp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(default='src/profile_bp/defaultAvatar.jpg', max_length=255, null=True, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profileBp',
            field=models.CharField(default='src/profile_bp/defaultBp.jpg', max_length=255, null=True, verbose_name='背景图片'),
        ),
    ]
