# Generated by Django 5.0.6 on 2024-06-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoSocialApp', '0006_alter_userprofile_avatar_alter_userprofile_profilebp'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='intimacy',
            field=models.CharField(default='0', max_length=255, verbose_name='情感密度'),
        ),
    ]
